# docker-compose.yml
version: '3'

services:
  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/ 
    ports:
      - 5044:5432

volumes:
  database-data: 