# docker-compose.yml
version: '3'

services:
  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5044:5432

# trying to remove volume for testing
# docker volume rm --force docker_database-data docker_db
volumes:
  db: